### PR TITLE
Test adding composer-lock diff to PRs to the main branch

### PR DESCRIPTION
**Pull request by lazysoundsystem**
This is to test https://github.com/UN-OCHA/common-design-site/pull/416

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
Okay, I imagined there was some more magic involved but I see now that this requires a commit to be useful. A shame. I'll think a bit more about whether this can be useful. Perhaps we could have a 'merge-to-main' action...

**Comment by lazysoundsystem** [comment]
@cafuego Just checking if you intended to add the SES support to this branch or to another - this branch was just a test and should be closed as it didn't do what I'd hoped it would, but I don't want to chuck out your SES changes if they should go elsewhere...

**Comment by lazysoundsystem** [comment]
Closing this, I'll be opening a normal deployment PR soon.

**Comment by cafuego** [comment]
> @cafuego Sorry, I previously left a comment thinking you'd added a commit to a different branch, not `develop`. Please ignore it!

Too late!

**Pull request closed without merging**
