### PR TITLE
tests: try running tests from within the containers

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-8328

Expecting this might fail the tests - but that I might learn something useful from that.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
@cafuego I've got blocked on the AWS bit:
`  - aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin public.ecr.aws/unocha`

I'm not sure why other properties use the same line in their .travis.yml but it's not working here. But then I don't know anything about AWS credentials. I've reverted my attempts to work around my lack of understanding and I'll try with a site with tests that already use this line.

**Comment by cafuego** [comment]
The credentials are per-repo only in Travis, so they're probably just missing from this one.

**Comment by lazysoundsystem** [comment]
If we're aiming to containerize travis tests on all repos - it might be worth adding the credentials. Happy to ask on a repo-by-repo basis. Can we add them for this one?

**Comment by cafuego** [comment]
We can - I already did - the latest fail is courtesy of SITEID not being set :-)

**Pull request closed without merging**
