### PR TITLE
[CD-515] GTM deferred

### PR DESCRIPTION
**Pull request by rupl**
# CD-515

Forked the [gtm_barebones](https://www.drupal.org/project/gtm_barebones) module after [confirming that the maintainer did not want to adopt the change](https://www.drupal.org/project/gtm_barebones/issues/3415279).

- Inline JS converted to an external script with `defer` attribute.
- All three config values are output to `drupalSettings` so that the module can output a static JS file that never needs rebuilding, even if config changes.
- No changes to any of the config; find-replace in Ansible should be possible to adopt this module (i.e. change `gtm_barebones` to `ocha_gtm`)

If people are happy with this, I'll put it in a standalone repo using the Drupal module as an upstream so that we can get security updates.

### CODE REVIEW

**Review by lazysoundsystem — APPROVED** [review]
Haven't diffed it against the original module, but it all looks right.

**Comment by attiks** [comment]
My 2 cents

- isn't it easier to use a patch instead of renaming? or will you clone it into unocha/gtm_barebones
- why not add a route for `ocha_gtm/js/gtm.js` that returns the js code, no more need for settings

**Comment by lazysoundsystem** [comment]
Some things that need fixing picked up in tests:
```
FILE: /srv/www/html/modules/custom/ocha_gtm/ocha_gtm.module
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | [x] Missing file doc comment
----------------------------------------------------------------------


FILE: /srv/www/html/modules/custom/ocha_gtm/js/gtm.js
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | File appears to be minified and cannot be processed
----------------------------------------------------------------------


FILE: /srv/www/html/modules/custom/ocha_gtm/src/Hooks/OchaGtmHooks.php
----------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
----------------------------------------------------------------------
  10 | WARNING | [x] Unused use statement
 102 | ERROR   | [x] Missing function doc comment
----------------------------------------------------------------------
```

**Comment by rupl** [comment]
So, we did end up forking the module into our GH org. Closing this prototype PR as it served its purpose.

**Pull request closed without merging**
