### PR TITLE
test: update E2E to match the upcoming change to OCHA Services

### PR DESCRIPTION
**Pull request by rupl**
Refs: CD-537, un-ocha/common_design@c5d5409e, https://github.com/UN-OCHA/common_design/pull/463

### CODE REVIEW

**Comment by rupl** [comment]
Whoops! It's not ready yet. It still needs to incorporate a tagged CD release.

**Comment by rupl** [comment]
Ok @left23 this is truly ready for review now.

**Review by left23 — APPROVED** [review]

**Comment by rupl** [comment]
He asked for one change. Before we deploy I'll wait for that CD PR to land https://github.com/UN-OCHA/common_design/pull/468

**Comment by rupl** [comment]
Javi approved in the ticket. Merging!

**Pull request merged**
